### ISSUE TITLE
JDynmapGriefprevention russian translation

### ISSUE THREAD

**Issue by jahangir13** [DmitryRendov/mob-server#9]
Hey Dmitry, didn't find any other way to contect you.
Can I use your russian translation of Messages_ru.properties for JDynmapGriefprevention to add it to my Spigot page of the plugin for others to download (https://www.spigotmc.org/resources/jdynmapgriefprevention.818/)?
Best regards, jahan.

**Comment by DmitryRendov** [comment]
Hi Jahan,

Sure. Please have a look at 0437d146da021e3af47809dc3e8571051428e7ac and 8704ccf2bdcd61e8b5ea307c201b899f371cf817

Let me know if you need anything else)
Thanks!
